//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaNoiParking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingImage
    {
        public int ImageID { get; set; }
        public int ParkingID { get; set; }
        public string ImagePath { get; set; }
    
        public virtual Parking Parking { get; set; }
    }
}
